### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Provide Name.")?

### ISSUE THREAD

**Issue by pprathameshmore** [amit-bhandari/instant-wallpaper-changer#3]
https://github.com/amit-bhandari/quick-wallpaper-changer-linux/blob/6385b562347e2d98a5e7aa89eeb7363de1598dc4/changewall_windows.py#L13

**Comment by amit-bhandari** [comment]
Hey Prathamesh, 

Script is written for Python 2 and you are trying to run it in python 3.

Regards.
