### ISSUE TITLE
New JS Problem

### ISSUE THREAD

**Issue by vinogcs** [amit-bhandari/instant-wallpaper-changer#6]
I think code is not working now, as page from Google is JS driven.  Do you got any idea to solve that issue?

**Comment by amit-bhandari** [comment]
It works for me as of now. What is the error you are getting

**Comment by vinogcs** [comment]
The page result from Google for me does not contain any DIV with attribute 'data-ri'. LOL. 
The sample output I'm getting is:

[text.txt](https://github.com/amit-bhandari/instant-wallpaper-changer/files/1743939/text.txt)

**Comment by amit-bhandari** [comment]
Script is working as of now
